"""Company profile database for ATS-targeted resume optimization.

Each profile captures the unique culture, leadership principles, preferred
language patterns, and evaluation criteria of a target company.
"""

from typing import Dict, List, Optional


CompanyProfile = Dict[str, object]

COMPANY_PROFILES: Dict[str, CompanyProfile] = {
    "apple": {
        "name": "Apple",
        "aliases": ["苹果", "apple inc", "apple inc."],
        "culture_keywords": [
            "design",
            "privacy",
            "innovation",
            "seamless",
            "user experience",
            "craftsmanship",
            "simplicity",
            "hardware-software integration",
            "ecosystem",
        ],
        "leadership_principles": [
            "Think different – challenge the status quo",
            "Design matters – every detail counts",
            "Privacy is a fundamental right",
            "Leave the world better than you found it",
            "Focus on the user experience above all else",
        ],
        "preferred_verbs": [
            "Designed",
            "Architected",
            "Pioneered",
            "Transformed",
            "Crafted",
            "Innovated",
            "Reimagined",
            "Refined",
        ],
        "avoid_verbs": [
            "Helped",
            "Participated",
            "Assisted",
        ],
        "impact_patterns": [
            "user experience improvement",
            "privacy enhancement",
            "design system",
            "cross-functional collaboration",
            "hardware-software integration",
        ],
        "resume_template": "creative_minimal",
        "quantification_style": "impact_on_users",
        "tips": [
            "强调设计作品和用户体验",
            "突出隐私相关项目",
            "展示跨团队协作能力",
            "强调软硬件整合经验",
            "简洁精炼，注重细节",
        ],
    },
    "google": {
        "name": "Google",
        "aliases": ["谷歌", "google llc", "alphabet"],
        "culture_keywords": [
            "scale",
            "AI/ML",
            "impact",
            "learning",
            "innovation",
            "open source",
            "data-driven",
            "billion users",
            "infrastructure",
            "research",
        ],
        "leadership_principles": [
            "Focus on the user, not just the product",
            "Build for scale – think billions",
            "Never stop learning and growing",
            "Innovation through experimentation",
            "Data beats opinions",
        ],
        "preferred_verbs": [
            "Scaled",
            "Deployed",
            "Optimized",
            "Launched",
            "Engineered",
            "Reduced",
            "Automated",
            "Researched",
        ],
        "avoid_verbs": [
            "Tried",
            "Attempted",
            "Hopefully",
        ],
        "impact_patterns": [
            "100M+ users",
            "99.9% uptime",
            "10x improvement",
            "reduced latency",
            "open-sourced",
        ],
        "resume_template": "technical_clean",
        "quantification_style": "technical_scale",
        "tips": [
            "量化技术规模(用户量、QPS、数据量)",
            "突出算法/ML相关项目",
            "展示学习能力和技术深度",
            "提及开源贡献和论文",
            "强调系统设计和分布式经验",
        ],
    },
    "amazon": {
        "name": "Amazon",
        "aliases": ["亚马逊", "amazon web services", "aws"],
        "culture_keywords": [
            "customer_obsession",
            "ownership",
            "bias_for_action",
            "frugality",
            "deliver results",
            "invent and simplify",
            "data-driven",
            "operational excellence",
        ],
        "leadership_principles": [
            "Customer Obsession",
            "Ownership",
            "Invent and Simplify",
            "Are Right, A Lot",
            "Learn and Be Curious",
            "Hire and Develop the Best",
            "Insist on the Highest Standards",
            "Think Big",
            "Bias for Action",
            "Frugality",
            "Earn Trust",
            "Dive Deep",
            "Have Backbone; Disagree and Commit",
            "Deliver Results",
        ],
        "preferred_verbs": [
            "Delivered",
            "Owned",
            "Reduced costs by",
            "Increased revenue by",
            "Launched",
            "Simplified",
            "Invented",
            "Dived deep into",
        ],
        "avoid_verbs": [
            "Maybe",
            "Probably",
            "Suggested",
        ],
        "impact_patterns": [
            "$ cost savings",
            "% revenue increase",
            "customer satisfaction",
            "operational efficiency",
            "process improvement",
        ],
        "resume_template": "achievement_focused",
        "quantification_style": "business_metrics",
        "tips": [
            "每个 bullet point 都要体现领导力准则",
            "用数字量化成就($、%、X倍)",
            "从客户问题出发描述项目",
            "强调 Ownership 和结果导向",
            "展示 Dive Deep 的数据分析能力",
        ],
    },
    "bytedance": {
        "name": "ByteDance",
        "aliases": ["字节跳动", "字节", "bytedance inc", "tiktok"],
        "culture_keywords": [
            "algorithm",
            "recommendation",
            "data-driven",
            "fast-paced",
            "A/B testing",
            "growth",
            "user engagement",
            "content understanding",
        ],
        "leadership_principles": [
            "Pursue the ultimate – aim for the best",
            "Be candid and direct",
            "Stay grounded and pragmatic",
            "Embrace diversity and inclusion",
            "Grow together, win together",
        ],
        "preferred_verbs": [
            "Optimized",
            "Iterated",
            "Boosted",
            "Scaled",
            "Experimented",
            "Improved",
            "Accelerated",
            "Tuned",
        ],
        "avoid_verbs": [
            "Maintained",
            "Managed",
            "Supervised",
        ],
        "impact_patterns": [
            "DAU/MAU improvement",
            "CTR increase",
            "retention rate",
            "A/B test significance",
            "algorithmic improvement",
        ],
        "resume_template": "data_algorithmic",
        "quantification_style": "growth_metrics",
        "tips": [
            "强调算法和推荐系统经验",
            "展示 A/B 测试和实验能力",
            "突出增长和用户参与度指标",
            "展示快节奏迭代经验",
            "量化算法优化效果(CTR、转化率等)",
        ],
    },
    "tencent": {
        "name": "Tencent",
        "aliases": ["腾讯", "tencent holdings", "wechat"],
        "culture_keywords": [
            "product sense",
            "scale",
            "DAU/MAU",
            "social",
            "payment",
            "gaming",
            "user-centric",
            "platform",
            "ecosystem",
        ],
        "leadership_principles": [
            "Value users – experience comes first",
            "Pursue excellence – craftsmanship in products",
            "Collaborate and grow together",
            "Build for hundreds of millions of users",
            "Technology for good",
        ],
        "preferred_verbs": [
            "Built",
            "Scaled",
            "Improved",
            "Launched",
            "Optimized",
            "Designed",
            "Expanded",
            "Evolved",
        ],
        "avoid_verbs": [
            "Ignored",
            "Assumed",
            "Guessed",
        ],
        "impact_patterns": [
            "DAU 100M+",
            "MAU growth",
            "payment volume",
            "social engagement",
            "platform scale",
        ],
        "resume_template": "product_engineering",
        "quantification_style": "user_scale",
        "tips": [
            "强调产品感和用户规模",
            "展示 DAU/MAU 级别项目经验",
            "突出社交、支付、游戏相关背景",
            "展示平台级系统架构能力",
            "强调 C 端产品经验",
        ],
    },
    "alibaba": {
        "name": "Alibaba",
        "aliases": ["阿里巴巴", "阿里", "alibaba group", "taobao", "蚂蚁"],
        "culture_keywords": [
            "business insight",
            "B2B/B2C",
            "internationalization",
            "Double 11",
            "e-commerce",
            "cloud",
            "data-driven",
            "platform economy",
        ],
        "leadership_principles": [
            "Customer first, employee second, shareholder third",
            "Because of trust, everything is simple",
            "Embrace change – the only constant is change",
            "Passion for innovation and breakthroughs",
            "Global vision, local execution",
        ],
        "preferred_verbs": [
            "Enabled",
            "Drove",
            "Generated",
            "Supported",
            "Achieved",
            "Empowered",
            "Facilitated",
            "Connected",
        ],
        "avoid_verbs": [
            "Failed",
            "Gave up",
            "Avoided",
        ],
        "impact_patterns": [
            "GMV contribution",
            "Double 11 peak handling",
            "merchant growth",
            "cross-border trade",
            "cloud infrastructure",
        ],
        "resume_template": "business_impact",
        "quantification_style": "business_revenue",
        "tips": [
            "强调商业洞察和业务贡献",
            "突出双11/大促经验(峰值QPS)",
            "展示 B2B/B2C 电商背景",
            "强调国际化和多语言能力",
            "展示技术驱动业务增长的案例",
        ],
    },
    "microsoft": {
        "name": "Microsoft",
        "aliases": ["微软", "msft"],
        "culture_keywords": [
            "growth mindset",
            "inclusive",
            "collaboration",
            "cloud",
            "enterprise",
            "open source",
            "accessibility",
            "AI democratization",
        ],
        "leadership_principles": [
            "Growth mindset – learn it all, not know it all",
            "Diversity and inclusion make us stronger",
            "One Microsoft – collaborate across boundaries",
            "Make a difference – create impact",
            "Think customer-first in everything",
        ],
        "preferred_verbs": [
            "Collaborated",
            "Enabled",
            "Shipped",
            "Integrated",
            "Solved",
            "Migrated",
            "Adopted",
            "Contributed",
        ],
        "avoid_verbs": [
            "Excluded",
            "Dominating",
            "Solo",
        ],
        "impact_patterns": [
            "enterprise adoption",
            "developer productivity",
            "cloud migration",
            "open source contribution",
            "accessibility improvement",
        ],
        "resume_template": "enterprise_collaborative",
        "quantification_style": "enterprise_scale",
        "tips": [
            "强调 Growth Mindset 和学习能力",
            "展示跨团队协作和包容性",
            "突出云服务和企业级产品经验",
            "展示开源贡献",
            "强调对开发者体验的关注",
        ],
    },
    "meta": {
        "name": "Meta",
        "aliases": ["facebook", "meta platforms", "instagram", "whatsapp"],
        "culture_keywords": [
            "move fast",
            "social impact",
            "AR/VR",
            "open source",
            "scale",
            "community",
            "metaverse",
            "connectivity",
        ],
        "leadership_principles": [
            "Move fast and build things",
            "Be bold and focus on impact",
            "Build social value",
            "Be open and transparent",
            "Focus on the long game",
        ],
        "preferred_verbs": [
            "Shipped",
            "Scaled",
            "Iterated",
            "Launched",
            "Experimented",
            "Grew",
            "Open-sourced",
            "Connected",
        ],
        "avoid_verbs": [
            "Delayed",
            "Hesitated",
            "Waited",
        ],
        "impact_patterns": [
            "billions of connections",
            "open source adoption",
            "community growth",
            "real-time at scale",
            "social impact metrics",
        ],
        "resume_template": "fast_impact",
        "quantification_style": "social_scale",
        "tips": [
            "强调快速迭代和交付能力",
            "展示大规模社交系统经验",
            "突出开源项目贡献",
            "展示对社交影响力的关注",
            "强调 Move Fast 的工程文化",
        ],
    },
    "huawei": {
        "name": "Huawei",
        "aliases": ["华为", "huawei technologies"],
        "culture_keywords": [
            "wolf culture",
            "hardcore engineering",
            "telecom",
            "5G",
            "chip design",
            "resilience",
            "self-reliance",
        ],
        "leadership_principles": [
            "Customer-centric – serve customers with dedication",
            "Dedicated – strive for excellence",
            "Persevere through challenges",
            "Continuous self-improvement",
            "Build a shared community",
        ],
        "preferred_verbs": [
            "Engineered",
            "Overcame",
            "Delivered",
            "Persevered",
            "Achieved",
            "Mastered",
            "Pioneered",
            "Transformed",
        ],
        "avoid_verbs": [
            "Complained",
            "Compromised",
            "Settled",
        ],
        "impact_patterns": [
            "carrier-grade reliability",
            "5G deployment",
            "chip breakthrough",
            "global coverage",
            "mission-critical systems",
        ],
        "resume_template": "engineering_resilient",
        "quantification_style": "engineering_rigor",
        "tips": [
            "强调吃苦耐劳和工程精神",
            "展示通信/网络领域深度",
            "突出底层技术(芯片、操作系统)经验",
            "展示抗压能力和坚韧品质",
            "强调技术自研和自主创新",
        ],
    },
    "netflix": {
        "name": "Netflix",
        "aliases": ["奈飞"],
        "culture_keywords": [
            "freedom and responsibility",
            "context not control",
            "high performance",
            "streaming",
            "content",
            "global",
            "A/B testing",
            "data-driven",
        ],
        "leadership_principles": [
            "Context, not control – empower with information",
            "Freedom and responsibility – act in Netflix's best interest",
            "Highly aligned, loosely coupled",
            "Lead with data, not opinions",
            "Build a team of stunning colleagues",
        ],
        "preferred_verbs": [
            "Decided",
            "Experimented",
            "Measured",
            "Scaled",
            "Streamed",
            "Personalized",
            "Automated",
            "Validated",
        ],
        "avoid_verbs": [
            "Asked permission",
            "Followed process",
            "Conformed",
        ],
        "impact_patterns": [
            "streaming quality",
            "A/B test results",
            "content recommendation",
            "global deployment",
            "chaos engineering",
        ],
        "resume_template": "autonomous_data",
        "quantification_style": "experimental_data",
        "tips": [
            "强调自主决策和责任感",
            "展示 A/B 测试和数据实验能力",
            "突出高并发流媒体经验",
            "展示 Chaos Engineering 实践",
            "强调 Context Not Control 的管理哲学",
        ],
    },
    "meituan": {
        "name": "Meituan",
        "aliases": ["美团", "meituan-dianping"],
        "culture_keywords": [
            "local services",
            "food delivery",
            "O2O",
            "on-demand",
            "urban lifestyle",
            "logistics",
            "efficiency",
        ],
        "leadership_principles": [
            "Customer first – create value for users",
            "Integrity and ethics above profits",
            "Embrace change and innovation",
            "Execute with excellence",
            "Long-term thinking over short-term gains",
        ],
        "preferred_verbs": [
            "Optimized",
            "Scaled",
            "Delivered",
            "Improved",
            "Launched",
            "Coordinated",
            "Integrated",
        ],
        "avoid_verbs": [
            "Overpromised",
            "Underperformed",
        ],
        "impact_patterns": [
            "delivery time reduction",
            "order volume increase",
            "merchant retention",
            "route efficiency",
            "user engagement",
        ],
        "resume_template": "operations_impact",
        "quantification_style": "operations_metrics",
        "tips": [
            "强调本地生活服务和 O2O 经验",
            "展示地推/商家运营能力",
            "突出履约效率和物流优化",
            "量化用户量和订单量增长",
            "强调执行力和长期思维",
        ],
    },
    "pinduoduo": {
        "name": "Pinduoduo",
        "aliases": ["拼多多", "pdd"],
        "culture_keywords": [
            "social commerce",
            "group buying",
            "C2M",
            "affordability",
            "viral growth",
            "gamification",
            "agriculture",
        ],
        "leadership_principles": [
            "Customer for less – make value accessible",
            "Social innovation – leverage collective power",
            "Extreme cost efficiency",
            "Rapid iteration and experimentation",
            "Embrace uncertainty and ambiguity",
        ],
        "preferred_verbs": [
            "Designed",
            "Iterated",
            "Viral",
            "Scaled",
            "Optimized",
            "Integrated",
            "Launched",
        ],
        "avoid_verbs": [
            "Waste",
            "Expensive",
            "Slow",
        ],
        "impact_patterns": [
            "viral coefficient",
            "C2M cost reduction",
            "GMV growth",
            "user acquisition cost",
            "social engagement",
        ],
        "resume_template": "growth_hacking",
        "quantification_style": "growth_metrics",
        "tips": [
            "强调社交电商和裂变增长经验",
            "展示 C2M 反向定制能力",
            "突出下沉市场和用户体验",
            "量化用户增长和获客成本",
            "展示极致性价比思维",
        ],
    },
    "xiaomi": {
        "name": "Xiaomi",
        "aliases": ["小米", "xiaomi corporation"],
        "culture_keywords": [
            "IoT",
            "smart hardware",
            "internet of things",
            "AIoT",
            "cost-effective",
            "user-centric",
            "innovation",
        ],
        "leadership_principles": [
            "User's friend – always do right by users",
            "Innovation for everyone – make technology accessible",
            "Build with passion",
            "Relentlessly pursue excellence",
            "Think bigger, move faster",
        ],
        "preferred_verbs": [
            "Designed",
            "Launched",
            "Integrated",
            "Optimized",
            "Scaled",
            "Delivered",
            "Innovated",
        ],
        "avoid_verbs": [
            "Compromised quality",
            "Overpriced",
        ],
        "impact_patterns": [
            "IoT device connections",
            "smart home ecosystem",
            "AIoT integration",
            "hardware cost reduction",
            "user ecosystem growth",
        ],
        "resume_template": "hardware_software",
        "quantification_style": "ecosystem_scale",
        "tips": [
            "强调 IoT 和智能硬件经验",
            "展示 AIoT 生态系统整合能力",
            "突出软硬件结合的产品思维",
            "量化硬件成本控制和用户体验",
            "展示生态连接和用户增长",
        ],
    },
    "stripe": {
        "name": "Stripe",
        "aliases": ["stripe inc", "条纹"],
        "culture_keywords": [
            "payments",
            "fintech",
            "developer-first",
            "API design",
            "reliability",
            "global infrastructure",
            "economic infrastructure",
        ],
        "leadership_principles": [
            "Build for the future – invest in long-term value",
            "Democratize the economy – make finance accessible",
            "Developer empathy – treat developers as customers",
            "Excellence in reliability",
            "Global ambition with local execution",
        ],
        "preferred_verbs": [
            "Designed",
            "Built",
            "Scaled",
            "Reliability",
            "Processed",
            "Reduced",
            "Optimized",
        ],
        "avoid_verbs": [
            "Overcomplicated",
            "Secured poorly",
        ],
        "impact_patterns": [
            "payment success rate",
            "transaction volume",
            "API latency reduction",
            "global coverage",
            "fraud reduction",
        ],
        "resume_template": "developer_infrastructure",
        "quantification_style": "reliability_metrics",
        "tips": [
            "强调支付和金融基础设施经验",
            "展示 API 设计和开发者体验思维",
            "突出高可靠性和容错设计",
            "量化交易规模和安全指标",
            "展示全球化支付基础设施经验",
        ],
    },
    "openai": {
        "name": "OpenAI",
        "aliases": ["openai inc", "open ai"],
        "culture_keywords": [
            "AI safety",
            "AGI",
            "alignment",
            "research",
            "language models",
            "deep learning",
            "safety-first",
        ],
        "leadership_principles": [
            "AGI safety – ensure AI benefits humanity",
            "Rigorous research – science first",
            "Transparency and openness",
            "Responsible deployment",
            "Long-term thinking on AI impact",
        ],
        "preferred_verbs": [
            "Researched",
            "Developed",
            "Aligned",
            "Evaluated",
            "Published",
            "Scaled",
            "Improved",
        ],
        "avoid_verbs": [
            "Deployed recklessly",
            "Ignored safety",
        ],
        "impact_patterns": [
            "model capability improvement",
            "safety benchmark scores",
            "research citations",
            "alignment research",
            "AI evaluation metrics",
        ],
        "resume_template": "research_engineering",
        "quantification_style": "research_metrics",
        "tips": [
            "强调 AI 安全和对齐研究经验",
            "展示大模型训练和评估能力",
            "突出研究论文和学术贡献",
            "量化模型性能和安全指标",
            "展示对 AGI 长期影响的思考",
        ],
    },
}


# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------


def get_profile(company: str) -> Optional[CompanyProfile]:
    """Look up a company profile by key or alias.

    Args:
        company: Company identifier (key, name, or alias).

    Returns:
        Company profile dict, or None if not found.
    """
    key = company.strip().lower()
    # Direct key match
    if key in COMPANY_PROFILES:
        return COMPANY_PROFILES[key]
    # Alias match
    for _key, profile in COMPANY_PROFILES.items():
        aliases = [a.lower() for a in profile.get("aliases", [])]
        if key in aliases or key == profile["name"].lower():
            return profile
    return None


def list_companies() -> List[str]:
    """Return all available company profile keys."""
    return list(COMPANY_PROFILES.keys())


def get_company_name(company: str) -> str:
    """Resolve a company identifier to its display name.

    Falls back to the original input if no profile is found.
    """
    profile = get_profile(company)
    if profile:
        return profile["name"]
    return company
